danceuk/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from accounts.views import register
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', register, name='register'),
    path('staff/login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('', include('pages.urls')),
    path('bookings/', include('bookings.urls')),
    path('teachers/', include('teachers.urls')),
    path('venues/', include('cities.urls')),
    path('contact/', include('contacts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from bookings.models import Booking



app_name='pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('job/<int:booking_id>/', views.job, name='job'),
    path('job/search/', views.job_search, name ='job-search')

]

teachers/urls.py
from django.urls import path
from .views import teacher_list, teachers_search, teacher_detail, TeacherUpdateView, TeacherCreateView


app_name = 'teachers'

urlpatterns = [
    path('', teacher_list, name='teachers'),
    path('teacher/<int:teacher_id>/', teacher_detail, name='teacher-detail'),
    path('teacher/<int:pk>/update/', TeacherUpdateView.as_view(), name='teacher-update' ),
    path('new', TeacherCreateView.as_view(), name='teacher-create'),
    path('search', teachers_search, name='teachers-search' )
]

teachers/models.py
from django.db import models
from cities.choices import city_choices
from django.urls import reverse


# Create your models here.

class Teacher(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    mobile = models.CharField(max_length=15)
    email = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True, default='static/img/default-teachers-pic.jpg')
    city = models.CharField(
        choices=city_choices,
        max_length=100,
        default=None
    )
    address = models.CharField(max_length=300, blank=True)
    postcode = models.CharField(max_length=10, blank=True)
    speciality = models.TextField()
    fee = models.IntegerField()
    notes = models.TextField(blank=True)
    dance_school_attended = models.CharField(max_length=200, blank=True)


    def __str__(self):
        return '{} {}'.format(
            self.first_name,
            self.last_name
        )

    def get_absolute_url(self):
        return reverse('teachers:teacher-detail', kwargs={'teacher_id': self.pk})

teachers/views.py
from django.shortcuts import render, get_object_or_404
from .models import Teacher
from cities.choices import city_choices, dance_styles
from django.views.generic import UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required




def authorised_only(function):

    def _inner(request, *args, **kwargs):
        if not request.user.is_staff:
            raise PermissionDenied
        return function(request, *args, **kwargs)
    return _inner


@login_required
@authorised_only
def teacher_list(request):
    teachers = Teacher.objects.all()

    context = {
        'teachers':teachers,
        'city_choices':city_choices,
        'dance_styles': dance_styles
    }

    return render(request, 'teachers/teachers.html', context)


@login_required
@authorised_only
def teacher_detail(request, teacher_id):

    teacher = get_object_or_404(Teacher, pk=teacher_id)

    context = {
        'teacher': teacher
    }
    return render(request, 'teachers/teachers-detail.html', context)



class TeacherUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Teacher
    template_name = 'teachers/teachers_form.html'
    fields = '__all__'

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False


class TeacherCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Teacher
    template_name = 'teachers/teachers_form.html'
    fields = '__all__'

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False



@login_required
@authorised_only
def teachers_search(request):

    queryset_list = Teacher.objects.all()



    if 'teachers_name' in request.GET:
        teachers_name = request.GET['teachers_name']
        if teachers_name:
            queryset_list = queryset_list.filter(first_name__icontains=teachers_name)

    # City
    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            queryset_list = queryset_list.filter(city__icontains=city)

    # Dance style
    if 'style' in request.GET:
        style = request.GET['style']
        if style:
            queryset_list = queryset_list.filter(speciality__icontains=style)


    context = {

        'teachers': queryset_list,
        'city_choices': city_choices,
        'dance_styles': dance_styles



    }
    return render(request, 'teachers/teachers_search.html', context)

templates/teachers/teachers-detail.html
{% extends 'base.html' %}


{% block content %}





    <div class="container" >
     <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'teachers:teachers' %}">Teachers</a> | {{ teacher.first_name }} {{ teacher.last_name }} </p>
            </div>
        </div>
    </div>


     <div class="row">
    <div class="col-12 col-sm-12 col-lg-9">
        {% if request.user.is_staff %}
        <a class="btn btn-info btn-sm float-right mb-2" href="{% url 'teachers:teacher-update' teacher.pk %}">Edit Teacher Detail</a>
        {% endif %}
    </div>
</div>




    <div class="booking-detail section">
    <div class="container" >
        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-lg-9 ">


                <div class="row">
        <div class="col-md-6">

            <img src="{{ teacher.photo.url }}" alt="pooop" class="img-fluid">

        </div>
        <div class="col-md-6">{{ teacher.first_name }} {{ teacher.last_name }} <br>
            {{ teacher.mobile }}<br>
            {{ teacher.email }}<br>
            {{ teacher.speciality }}<br>
            {{ teacher.address }}<br>
            {{ teacher.city }}<br>
            {{ teacher.postcode }}<br>
            £{{ teacher.fee }}ph<br>
            {{ teacher.notes }}<br>
        </div>
    </div>




            </div>
        </div>
    </div>
    </div>



{% endblock %}

templates/teachers/teachers.html
{% extends 'base.html' %}

{% block content %}


     <section id="showcase">
    <div class="container text-center">
      <div class="home-search p-5">
        <div class="overlay p-5">


          <div class="search">
            <form action="{% url 'teachers:teachers-search' %}">
              <!-- Form Row 1 -->
              <div class="form-row">

              <div class="col-md-4 mb-3">
                  <label class="sr-only">Name</label>
                  <input type="text" name="teachers_name" class="form-control" placeholder="Name (first name)">
                </div>

              <div class="col-md-4 mb-3">
                  <label class="sr-only">Dance Style</label>
                  <select name="style" class="form-control">
                    <option selected="true" disabled="disabled">Dance Style (All)</option>
                    {% for key,value in dance_styles %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                  </select>
                </div>



                <div class="col-md-4 mb-3">
                  <label class="sr-only">City</label>
                  <select name="city" class="form-control">
                    <option selected="true" disabled="disabled">City (All)</option>
                    {% for key,value in city_choices %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                  </select>
                </div>
              </div>
              <!-- Form Row 2 -->

              <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>


         <h1>Teachers</h1>

    <div class="row mb-2">
    <div class="col-md-12 text-right">
        <a class="btn btn-outline-primary" href="{% url 'teachers:teacher-create' %}">Add Teacher</a>
    </div>
    </div>

    <div class="row">
        <div class="col-md-12 mx-auto">
            {% if teachers %}
         <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
        <th scope="col">Mobile</th>
      <th scope="col">City</th>
      <th scope="col">Style</th>



    </tr>
  </thead>
  <tbody>
  {% for teacher in teachers %}
    <tr>
      <th scope="row">{{ teacher.id }}</th>
      <td><a href="{% url 'teachers:teacher-detail' teacher.id %}">{{ teacher.first_name}} {{ teacher.last_name }}</a></td>
        <td>{{ teacher.mobile }}</td>
      <td>{{ teacher.city }}</td>
      <td>{{ teacher.speciality }}</td>

    </tr>
    {% endfor %}
  </tbody>
</table>
    {% else %}
                <p>There are currently no teachers</p>
    {% endif %}
        </div>
    </div>



{% endblock %}

templates/teachers/teachers_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 mt-3">
                 <h4> Add / Update Teacher </h4>
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit">Create</button>
                    </form>
            </div>
            <div class="col-md-2"></div>

        </div>
    </div>

{% endblock %}

templates/teachers/teachers_search.html
{% extends 'base.html' %}

{% block content %}


     <section id="showcase">
    <div class="container text-center">
      <div class="home-search p-5">
        <div class="overlay p-5">


          <div class="search">
            <form action="{% url 'teachers:teachers-search' %}">
              <!-- Form Row 1 -->
              <div class="form-row">

              <div class="col-md-4 mb-3">
                  <label class="sr-only">Name</label>
                  <input type="text" name="teachers_name" class="form-control" placeholder="Name (first name)">
                </div>

              <div class="col-md-4 mb-3">
                  <label class="sr-only">Dance Style</label>
                  <select name="style" class="form-control">
                    <option selected="true" disabled="disabled">Dance Style (All)</option>
                    {% for key,value in dance_styles %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                  </select>
                </div>



                <div class="col-md-4 mb-3">
                  <label class="sr-only">City</label>
                  <select name="city" class="form-control">
                    <option selected="true" disabled="disabled">City (All)</option>
                    {% for key,value in city_choices %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                  </select>
                </div>
              </div>
              <!-- Form Row 2 -->

              <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>


         <h1>Teachers</h1>

    <div class="row mb-2">
    <div class="col-md-12 text-right">
        <a class="btn btn-outline-primary" href="{% url 'teachers:teacher-create' %}">Add Teacher</a>
    </div>
    </div>

    <div class="row">
        <div class="col-md-12 mx-auto">
            {% if teachers %}
         <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
        <th scope="col">Mobile</th>
      <th scope="col">City</th>
      <th scope="col">Style</th>



    </tr>
  </thead>
  <tbody>
  {% for teacher in teachers %}
    <tr>
      <th scope="row">{{ teacher.id }}</th>
      <td><a href="{% url 'teachers:teacher-detail' teacher.id %}">{{ teacher.first_name}} {{ teacher.last_name }}</a></td>
        <td>{{ teacher.mobile }}</td>
      <td>{{ teacher.city }}</td>
      <td>{{ teacher.speciality }}</td>

    </tr>
    {% endfor %}
  </tbody>
</table>
    {% else %}
                <p>There are currently no teachers</p>
    {% endif %}
        </div>
    </div>



{% endblock %}