bookings/urls.py
from django.urls import path
from .views import bookings, booking, BookingCreateView, BookingUpdateView, search, BookingDeleteView


app_name = 'bookings'

urlpatterns = [
    path('', bookings, name='bookings'),
    path('booking/<int:booking_id>/', booking, name='booking'),
    path('create', BookingCreateView.as_view(), name='booking-create'),
    path('booking/update/<int:pk>/', BookingUpdateView.as_view(), name='booking-update'),
    path('booking/delete/<int:pk>/', BookingDeleteView.as_view(), name='booking-delete'),
    path('search', search, name='search'),


]

cities/urls.py
from django.urls import path
from .views import venues, venue_detail, VenueUpdateView,VenueCreateView, venue_search


app_name='cities'

urlpatterns = [

    path('', venues, name='venues'),
    path('venue/<int:venue_id>/', venue_detail, name='venue-detail'),
    path('venue/<int:pk>/update', VenueUpdateView.as_view(), name='venue-update'),
    path('new/', VenueCreateView.as_view(), name='venue-create' ),
    path('search/', venue_search, name='venue-search')


]

contacts/urls.py
from django.urls import path
from .views import contact, contact_list, contact_detail, contact_search

app_name = 'contact'

urlpatterns = [

    path('contact', contact, name='contact'),
    path('contact/messages/', contact_list, name='contacts-list'),
    path('messages/<int:contact_id>/', contact_detail, name='contact-details'),
    path('contact/message/search/', contact_search, name='contact-search')
]

danceuk/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from accounts.views import register
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', register, name='register'),
    path('staff/login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('', include('pages.urls')),
    path('bookings/', include('bookings.urls')),
    path('teachers/', include('teachers.urls')),
    path('venues/', include('cities.urls')),
    path('contact/', include('contacts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from bookings.models import Booking



app_name='pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('job/<int:booking_id>/', views.job, name='job'),
    path('job/search/', views.job_search, name ='job-search')

]

teachers/urls.py
from django.urls import path
from .views import teacher_list, teachers_search, teacher_detail, TeacherUpdateView, TeacherCreateView


app_name = 'teachers'

urlpatterns = [
    path('', teacher_list, name='teachers'),
    path('teacher/<int:teacher_id>/', teacher_detail, name='teacher-detail'),
    path('teacher/<int:pk>/update/', TeacherUpdateView.as_view(), name='teacher-update' ),
    path('new', TeacherCreateView.as_view(), name='teacher-create'),
    path('search', teachers_search, name='teachers-search' )
]

templates/partials/_admin_navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/partials/_dances_common.html
<p>
  <span class="exsadie">
      Our Dance Instructors
  </span>
    <br>
    Our teachers are professional trained dancers who not only teach but perform on stage in concerts have experience with choreography to make your dance hen party an activity to remember!!!!!

</p>


<p> <span class="exsadie">
    What to bring<br>
</span>
Cameras so you can capture all the fun.
Hen parties throughout the UK </p>

<p><span class="exsadie">
    When and where <br>
</span>
We can hold your hen party on any day of the week, at a time to suit you in a location close to your day or night out- morning or afternoons. </p>

<p>
    <span class="exsadie"> Price  </span>
    <br>

    <ul>
                        <ol>
                            1 hr dance party your party is £{{ booking.cost|add:"-30" }}  + the cost of the venue (from £20ph) <br>

                        </ol>
            OR
                        <ol>
                            1.5hr dance Party your party is £{{ booking.cost }} + the cost of the venue  (from £20ph) <br>

                        </ol>
    </ul>


{% if booking.discount %}
                plus an additional  £{{ booking.discount }} off !! if booked before the {{ booking.book_before_date|date:"l jS   F Y" }} <br>

{% endif %}


</p>

<p>
    <span class="exsadie">Bubbly</span><br>
    You can add a  bottle of bubbly for the bride for an extra £10
</p>


<p>
    <span class="exsadie"> To Book  </span>
    <br>
    Just give us a call 07846518558 or email {{ booking.city.email }} to discuss your requirements or fill in the form and a member of our team will get back in touch with you

</p>
<p>
    Kind regards <br>
    Dance Hen Parties<br>
Admin team
</p>

templates/partials/_footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center"> &copy : DanceCentreUk </p>

</div>

templates/partials/_header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/partials/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'pages:index' %}">jobs</a>
      </li>






    </ul>



    <ul class="navbar-nav ml-auto">
        {% if user.is_staff %}

            <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ request.user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'bookings:bookings' %}">Bookings</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'teachers:teachers' %}">Teachers</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'cities:venues' %}">Venues</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'contact:contacts-list' %}">Messages</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}"><i class="fas fa-sign-in-alt"></i>LOGOUT</a>

        </div>
      </li>




        {% else %}


        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">
                <i class="fas fa-sign-in-alt"></i>
                Login</a>
        </li>
        {% endif %}



    </ul>



  </div>
</nav>