contacts/urls.py
from django.urls import path
from .views import contact, contact_list, contact_detail, contact_search

app_name = 'contact'

urlpatterns = [

    path('contact', contact, name='contact'),
    path('contact/messages/', contact_list, name='contacts-list'),
    path('messages/<int:contact_id>/', contact_detail, name='contact-details'),
    path('contact/message/search/', contact_search, name='contact-search')
]

danceuk/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from accounts.views import register
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', register, name='register'),
    path('staff/login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('', include('pages.urls')),
    path('bookings/', include('bookings.urls')),
    path('teachers/', include('teachers.urls')),
    path('venues/', include('cities.urls')),
    path('contact/', include('contacts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from bookings.models import Booking



app_name='pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('job/<int:booking_id>/', views.job, name='job'),
    path('job/search/', views.job_search, name ='job-search')

]

templates/pages/index.html
{% extends 'base.html' %}


{% block content %}



     <section id="showcase">
    <div class="container text-center">
      <div class="home-search p-5">
        <div class="overlay p-5">


          <div class="search">
            <form action="{% url 'pages:job-search' %}">
              <!-- Form Row 1 -->
              <div class="form-row">

              <div class="col-md-4 mb-3">
                  <label class="sr-only">Dance Style</label>
                  <select name="style" class="form-control">
                    <option selected="true" disabled="disabled">Dance Style (All)</option>
                    {% for key,value in dance_choices %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                  </select>
                </div>

                <div class="col-md-4 mb-3">
                  <label class="sr-only">Teacher Booked</label>
                  <select name="teacher_booked" class="form-control">
                    <option selected="true" disabled="disabled">Teacher Confirmed (All)</option>
                    {% for key,value in options %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                  </select>
                </div>

                <div class="col-md-4 mb-3">
                  <label class="sr-only">City</label>
                  <select name="city" class="form-control">
                    <option selected="true" disabled="disabled">City (All)</option>
                    {% for key,value in city_choices %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                  </select>
                </div>
              </div>
              <!-- Form Row 2 -->

              <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>











        <h1>Current Bookings</h1>

    <div class="row">
        <div class="col-md-12 mx-auto">
            {% if bookings %}
         <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">City</th>
      <th scope="col">Style</th>

      <th scope="col">Date</th>
      <th scope="col">Client Confirmed</th>
      <th scope="col">Teacher Booked</th>

    </tr>
  </thead>
  <tbody>
  {% for booking in bookings %}
    <tr>
      <th scope="row">{{ booking.id }}</th>
      <td><a href="{% url 'pages:job' booking.id %}">{{ booking.name|truncatewords:1}}</a></td>
      <td>{{ booking.city }}</td>
      <td>{{ booking.dance_style }}</td>
      <td>{{ booking.event_date }}</td>
      <td>{% if booking.booking_sent == True %}
          <span class="true_button">confirmed</span>
          {% else %}
          <span class="false_button">Not Confirmed</span>
          {% endif %}
      </td>

      <td>{% if booking.teacher_confirmed == True %}
          <span class="true_button">Booked</span>
          {% else %}
          <span class="false_button">Not Booked</span>
          {% endif %}

      </td>


    </tr>
    {% endfor %}
  </tbody>
</table>
    {% else %}
        <p>You currently have no bookings</p>
    {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            {% if bookings.has_other_pages %}
              <ul class="pagination">
               {% if bookings.has_previous %}
                   <li class="page-item">
                        <a class="page-link" href="?page={{ bookings.previous_page_number }}">&laquo;</a>
                    </li>
               {% else %}
                   <li class="page-item disabled">
                      <a class="page-link" >&laquo;</a>
                    </li>
               {% endif %}
              {% for i in bookings.paginator.page_range %}
                  {% if bookings.number == i %}
                      <li class="page-item active">
                          <a class="page-link">{{ i }}</a>
                        </li>
                  {% else %}
                      <li class="page-item">
                          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                      </li>
                  {% endif %}
              {% endfor %}
              {% if bookings.has_next %}
                   <li class="page-item">
                        <a class="page-link" href="?page={{ bookings.next_page_number }}">&raquo;</a>
                    </li>
               {% else %}
                   <li class="page-item disabled">
                      <a class="page-link" >&raquo;</a>
                    </li>
               {% endif %}

              </ul>
            {% endif %}
        </div>
      </div>
    </div>






{% endblock %}

templates/pages/job_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container" >
     <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'pages:index' %}">Bookings</a> | {{ booking.id }} </p>
            </div>
        </div>
    </div>


     <div class="row">
    <div class="col-12 col-sm-12 col-lg-9">

                  <button class="btn-info  btn-sm float-right mb-2 "  data-toggle="modal" data-target="#inquiryModal">Apply fot this Job</button>


    </div>
</div>




    <div class="booking-detail section">
    <div class="container" >
        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-lg-9 ">




                <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th scope="col">Job Summary</th>
                          <th scope="col">{{ booking.dance_style }} Dance hen party in {{ booking.city }} <br>
                              {{ booking.event_date|date:"l jS   F Y" }} from {{ booking.start_time }}-{{ booking.end_time }}
                          </th>
                        </tr>
                      </thead>
                      <tbody>

                        <tr>
                          <th scope="row">Booking id</th>
                          <td>{{ booking.id  }}</td>
                        </tr>
                        <tr>
                          <th scope="row">Contact Person</th>
                          <td>{{ booking.name | truncatewords:1 }}</td>
                        </tr>

                        <tr>
                          <th scope="row">City</th>
                          <td>{{ booking.city  }}</td>
                        </tr>



                        <tr>
                            <th>Date of Event :</th>
                            <td>{{ booking.event_date|date:"l jS   F Y" }}</td>
                        </tr>
                        <tr>
                            <th>Time of Event :</th>
                            <td>{{ booking.start_time }}-{{ booking.end_time  }}</td>
                        </tr>
                        <tr>
                            <th>Dance Style :</th>
                            <td>{{ booking.dance_style }}</td>
                        </tr>




                         <tr>
                            <td>Workshop Booked</td>
                            <td>{% if booking.booking_sent == False %}
                                <button type="button" class="btn-danger btn-sm ">not Booked</button>
                                {% else %}
                                <button type="button" class="btn-info btn-sm">Booked</button>
                                {% endif %}

                            </td>
                        </tr>


                      <tr>
                            <td>Teacher Confirmed</td>
                            <td>
                                {% if booking.teacher_confirmed == False %}
                                <button type="button" class="btn-danger btn-sm ">Teacher NOT confirmed</button>
                                {% else %}
                                <button type="button" class="btn-info btn-sm">Teacher Confirmed</button>
                                {% endif %}
                            {% if booking.teacher_confirmed == True %}
                                <br><br><p>
                            Although a  teacher is booked you can still apply for this position incase the vacancy becomes
                            available
                            </p>
                            {% endif %}

                            </td>
                        </tr>





                      </tbody>
                    </table>


            </div>
        </div>



    </div>
    </div>



      <!-- Inquiry Modal -->
  <div class="modal fade" id="inquiryModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="inquiryModalLabel">Apply for this Job</h5>
          <button type="button" class="close" data-dismiss="modal">
            <span>&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="{% url 'contact:contact' %}" method="POST">
              {% csrf_token %}
              {% if user.is_authenticated %}
                  <input type="hidden" name="user_id" value="{{ user.id }}">
              {% else %}
                  <input type="hidden" name="user_id" value="0">
              {% endif %}

              <input type="hidden" name="booking_id" value="{{ booking.id }}">
              <input type="hidden" name="booking_city" value="{{ booking.city }}">

            <div class="form-group">
              <label for="booking_name" class="col-form-label">Booking Name:</label>
              <input type="text" name="booking_name" class="form-control"
                     value="{{ booking.id }} : {{ booking.dance_style }} hen party  in {{ booking.city }} on {{ booking.event_date }}" >
            </div>
            <div class="form-group">
              <label for="name" class="col-form-label">Name:</label>
              <input type="text" name="name" class="form-control"
                     {% if user.is_authenticated %} value="{{ user.name }}" {% endif %} required>
            </div>
            <div class="form-group">
              <label for="email" class="col-form-label">Email:</label>
              <input type="email" name="email" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="mobile" class="col-form-label">Mobile:</label>
              <input type="text" name="mobile" class="form-control">
            </div>
            <div class="form-group">
              <label for="message" class="col-form-label">Message:</label>
              <textarea name="message" class="form-control"></textarea>
            </div>
          <div class="form-group">
              <label for="contact_city" class="col-form-label">City:</label>
              <input type="contact_city" name="contact_city" class="form-control" placeholder="City you reside in" required>
            </div>
            <div class="form-group">
              <label for="dance_school" class="col-form-label">Dance School Attended:</label>
              <input type="text" name="dance_school" class="form-control" placeholder="Ps let us know dance school attended if its your first time applying">
            </div>
            <div class="form-group">
              <label for="experience" class="col-form-label">Experience:</label>
              <textarea name="experience" class="form-control" placeholder="Ps let us know dance expeience if its your first time applying"></textarea>
            </div>

            <hr>
            <input type="submit" value="Send" class="btn btn-block btn-secondary">
          </form>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

templates/pages/job_search.html
{% extends 'base.html' %}


{% block content %}


    <section id="showcase">
    <div class="container text-center">
      <div class="home-search p-5">
        <div class="overlay p-5">


          <div class="search">
            <form action="{% url 'pages:job-search' %}">
              <!-- Form Row 1 -->
              <div class="form-row">

              <div class="col-md-4 mb-3">
                  <label class="sr-only">Dance Style</label>
                  <select name="style" class="form-control">
                    <option selected="true" disabled="disabled">Dance Style (All)</option>
                    {% for key,value in dance_choices %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                  </select>
                </div>

                <div class="col-md-4 mb-3">
                  <label class="sr-only">Teacher Booked</label>
                  <select name="teacher_booked" class="form-control">
                    <option selected="true" disabled="disabled">Teacher Confirmed (All)</option>
                    {% for key,value in options %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                  </select>
                </div>

                <div class="col-md-4 mb-3">
                  <label class="sr-only">City</label>
                  <select name="city" class="form-control">
                    <option selected="true" disabled="disabled">City (All)</option>
                    {% for key,value in city_choices %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                  </select>
                </div>
              </div>
              <!-- Form Row 2 -->

              <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>


         <h1>Current Bookings</h1>

    <div class="row">
        <div class="col-md-12 mx-auto">
            {% if bookings %}
         <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">City</th>
      <th scope="col">Style</th>

      <th scope="col">Date</th>
      <th scope="col">Client Confirmed</th>
      <th scope="col">Teacher Booked</th>

    </tr>
  </thead>
  <tbody>
  {% for booking in bookings %}
    <tr>
      <th scope="row">{{ booking.id }}</th>
      <td><a href="{% url 'pages:job' booking.id %}">{{ booking.name|truncatewords:1}}</a></td>
      <td>{{ booking.city }}</td>
      <td>{{ booking.dance_style }}</td>
      <td>{{ booking.event_date }}</td>
      <td>{{ booking.booking_sent }}</td>
      <td>{{ booking.teacher_confirmed }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
    {% else %}
        <p>There are currently no bookings matching your description ps widen your search or look back later we get new bookings on a  regular basis daily</p>
    {% endif %}
        </div>
    </div>


{% endblock %}

templates/pages/jobs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>