cities/urls.py
from django.urls import path
from .views import venues, venue_detail, VenueUpdateView,VenueCreateView, venue_search


app_name='cities'

urlpatterns = [

    path('', venues, name='venues'),
    path('venue/<int:venue_id>/', venue_detail, name='venue-detail'),
    path('venue/<int:pk>/update', VenueUpdateView.as_view(), name='venue-update'),
    path('new/', VenueCreateView.as_view(), name='venue-create' ),
    path('search/', venue_search, name='venue-search')


]

danceuk/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from accounts.views import register
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', register, name='register'),
    path('staff/login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('', include('pages.urls')),
    path('bookings/', include('bookings.urls')),
    path('teachers/', include('teachers.urls')),
    path('venues/', include('cities.urls')),
    path('contact/', include('contacts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from bookings.models import Booking



app_name='pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('job/<int:booking_id>/', views.job, name='job'),
    path('job/search/', views.job_search, name ='job-search')

]

cities/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class City(models.Model):
    name = models.CharField(max_length=200, help_text='Enter the City name')

    class Meta:
        ordering = ('-name',)

    def __str__(self):
        return self.name


class Studio(models.Model):
    studio_name = models.CharField(max_length=200, help_text='Enter Studio or website name')
    city = models.ForeignKey(City, on_delete=models.DO_NOTHING)
    studio_website = models.URLField(max_length=200, blank=True)
    studio_email = models.CharField(max_length=200, help_text='Enter Studio contact')
    studio_mobile = models.CharField(max_length=15, help_text='Enter contact number')
    studio_contact = models.CharField(max_length=200, default='James Cooke')

    def __str__(self):
        return self.studio_name


class Venue(models.Model):
    venue_name = models.CharField(max_length=200)
    address = models.CharField(max_length=300,  blank=True)
    city = models.ForeignKey(City, on_delete=models.DO_NOTHING)
    postcode = models.CharField(max_length=10, blank=True)
    venue_phone = models.CharField(max_length=20,  blank=True)
    venue_coordinator = models.CharField(max_length=200, blank=True)
    venue_email = models.CharField(max_length=300,  blank=True)
    venue_website = models.URLField(max_length=200,  blank=True)
    capacity = models.IntegerField(blank=True)
    cost = models.IntegerField( blank=True)
    no_studios = models.IntegerField(default=1)
    photo_main = models.ImageField(upload_to='photos/venue/%Y/%m/%d/', blank=True)
    photo_1 = models.ImageField(upload_to='photos/venue/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/venue/%Y/%m/%d/', blank=True)
    notes = models.TextField(blank=True)



    def __str__(self):
        return self.venue_name

    def get_absolute_url(self):
        return reverse('cities:venue-detail', kwargs={'venue_id': self.pk})

cities/views.py
from django.shortcuts import render, get_object_or_404
from .models import Venue
from django.views.generic import UpdateView, CreateView
from .choices import city_choices
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


# Create your views here.

def authorised_only(function):

    def _inner(request, *args, **kwargs):
        if not request.user.is_staff:
            raise PermissionDenied
        return function(request, *args, **kwargs)
    return _inner

@login_required
@authorised_only
def venues(request):
    venues = Venue.objects.all()

    context = {
        'venues': venues,
        'city_choices': city_choices
    }

    return render(request, 'cities/venues.html', context)


@login_required
@authorised_only
def venue_detail(request, venue_id):

    venue = get_object_or_404(Venue, pk=venue_id)

    context = {

        'venue': venue

    }
    return render(request, 'cities/venue-detail.html', context)


class VenueCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Venue
    template_name = 'cities/venue_form.html'
    fields = '__all__'

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False


class VenueUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Venue
    template_name = 'cities/venue_form.html'
    fields = '__all__'

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False


@login_required
@authorised_only
def venue_search(request):

    queryset_list = Venue.objects.all()

    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            queryset_list = queryset_list.filter(city__name__icontains=city)


    context ={
        'venues': queryset_list,
        'city_choices': city_choices
    }
    return render(request, 'cities/venue_search.html', context)

templates/cities/venue-detail.html
{% extends 'base.html' %}


{% block content %}





    <div class="container" >
     <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'cities:venues' %}">Venues</a> | {{ venue.venue_name }} </p>
            </div>
        </div>
    </div>


     <div class="row">
    <div class="col-12 col-sm-12 col-lg-9">
        {% if request.user.is_staff %}
        <a class="btn btn-info btn-sm float-right mb-2" href="{% url 'cities:venue-update'  venue.pk %}">Edit Venue Detail</a>
        {% endif %}
    </div>
</div>




    <div class="booking-detail section">
    <div class="container" >
        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-lg-9 ">


               <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th scope="col">Venue Name</th>
                          <th scope="col">{{ venue.venue_name }}
                          </th>
                        </tr>
                      </thead>
                      <tbody>

                        <tr>
                          <th scope="row">Venue Address</th>
                          <td>{{ venue.address }}</td>
                        </tr>
                        <tr>
                          <th scope="row">City</th>
                          <td>{{ venue.city }}</td>
                        </tr>

                        <tr>
                          <th scope="row">Email</th>
                          <td>{{ venue.venue_email }}</td>
                        </tr>



                        <tr>
                            <th>Contant Number</th>
                            <td>{{venue.venue_phone }}</td>
                        </tr>
                        <tr>
                            <th>Coordinator</th>
                            <td>{{ venue.venue_coordinator }}</td>
                        </tr>
                        <tr>
                            <th>Website</th>
                            <td>{{ venue.venue_website }}</td>
                        </tr>
                        <tr>
                            <th>Capacity</th>
                            <td>{{ venue.capacity }}</td>
                        </tr>
                        <tr>
                            <th>Cost</th>
                            <td>{{ venue.cost }}</td>
                        </tr>
                        <tr>
                            <th>No of Studios</th>
                            <td>{{ venue.no_studios }}</td>
                        </tr>
                        <tr>
                            <th>Notes</th>
                            <td>{{ venue.notes }}</td>
                        </tr>

                      </tbody>
                    </table>




            </div>


            <div class="row">
            <div class="col-md-4">
                {% if venue.photo_main %}
                    <img src="{{ venue.photo_main.url}}" alt="pooop" class="img-fluid">
                {% endif %}
            </div>
            <div class="col-md-4">
                {% if venue.photo_1 %}
                    <img src="{{ venue.photo_1.url}}" alt="{{ venue.venue_name }}" class="img-fluid">
                {% endif %}
            </div>



            </div>










        </div>
    </div>
    </div>



{% endblock %}

templates/cities/venue_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 mt-3">
                 <h4> Add / Update Venue </h4>
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit">Create</button>
                    </form>
            </div>
            <div class="col-md-2"></div>

        </div>
    </div>

{% endblock %}

templates/cities/venue_search.html
{% extends 'base.html' %}

{% block content %}


     <section id="showcase">
    <div class="container text-center">
      <div class="home-search p-5">
        <div class="overlay p-5">


          <div class="search">
            <form action="{% url 'cities:venue-search' %}">
              <!-- Form Row 1 -->
              <div class="form-row">







                <div class="offset-3 col-md-6 mb-3">
                  <label class="sr-only">City</label>
                  <select name="city" class="form-control">
                    <option selected="true" disabled="disabled">City (All)</option>
                    {% for key,value in city_choices %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                  </select>
                </div>
              </div>
              <!-- Form Row 2 -->

              <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>


         <h1>Venues</h1>

    <div class="row mb-2">
    <div class="col-md-12 text-right">
        <a class="btn btn-outline-primary" href="{% url 'cities:venue-create' %}">Add Venue</a>
    </div>
    </div>

    <div class="row">
        <div class="col-md-12 mx-auto">
            {% if venues %}
         <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
        <th scope="col">Phone</th>
        <th scope="col">Email</th>
        <th scope="col">Coordinator</th>
      <th scope="col">City</th>
      <th scope="col">cost</th>



    </tr>
  </thead>
  <tbody>
  {% for venue in venues %}
    <tr>
      <th scope="row">{{ venue.id }}</th>
      <td><a href="{% url 'cities:venue-detail' venue.id %}">{{ venue.venue_name }}</a></td>
        <td>{{ venue.venue_phone }}</td>
      <td>{{ venue.venue_email }}</td>
      <td>{{ venue.venue_coordinator }}</td>
      <td>{{ venue.city }}</td>
      <td>£{{ venue.cost }} ph</td>

    </tr>
    {% endfor %}
  </tbody>
</table>
    {% else %}
                <p>There are currently no venues that match your search</p>
    {% endif %}
        </div>
    </div>



{% endblock %}

templates/cities/venues.html
{% extends 'base.html' %}

{% block content %}


     <section id="showcase">
    <div class="container text-center">
      <div class="home-search p-5">
        <div class="overlay p-5">


          <div class="search">
            <form action="{% url 'cities:venue-search' %}">
              <!-- Form Row 1 -->
              <div class="form-row">







                <div class="offset-3 col-md-6 mb-3">
                  <label class="sr-only">City</label>
                  <select name="city" class="form-control">
                    <option selected="true" disabled="disabled">City (All)</option>
                    {% for key,value in city_choices %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                  </select>
                </div>
              </div>
              <!-- Form Row 2 -->

              <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>


         <h1>Venues</h1>

    <div class="row mb-2">
    <div class="col-md-12 text-right">
        <a class="btn btn-outline-primary" href="{% url 'cities:venue-create' %}">Add Venue</a>
    </div>
    </div>

    <div class="row">
        <div class="col-md-12 mx-auto">
            {% if venues %}
         <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
        <th scope="col">Phone</th>
        <th scope="col">Email</th>
        <th scope="col">Coordinator</th>
      <th scope="col">City</th>
      <th scope="col">cost</th>



    </tr>
  </thead>
  <tbody>
  {% for venue in venues %}
    <tr>
      <th scope="row">{{ venue.id }}</th>
      <td><a href="{% url 'cities:venue-detail' venue.id %}">{{ venue.venue_name }}</a></td>
        <td>{{ venue.venue_phone }}</td>
      <td>{{ venue.venue_email }}</td>
      <td>{{ venue.venue_coordinator }}</td>
      <td>{{ venue.city }}</td>
      <td>£{{ venue.cost }} ph</td>

    </tr>
    {% endfor %}
  </tbody>
</table>
    {% else %}
                <p>There are currently no teachers</p>
    {% endif %}
        </div>
    </div>



{% endblock %}